CREATE TABLE "usuario" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "rol" varchar(50) NOT NULL,
  "activo" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

-- cliente unchanged
CREATE TABLE "cliente" (
  "id_cliente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int UNIQUE NOT NULL,
  "telefono" varchar(20),
  "direccion" varchar(255)
);

CREATE TABLE "unidad_medida" (
  "id_unidad" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL,
  "tipo" varchar(50) NOT NULL,
  "abreviatura" varchar(10) NOT NULL,
  "activo" boolean DEFAULT true
);

CREATE TABLE "producto" (
  "id_producto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(50) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "descripcion" text,
  "id_unidad" int NOT NULL,
  "contenido" decimal(10,2),
  "precio" decimal(10,2) NOT NULL,
  "stock" int DEFAULT 0,
  "activo" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "insumo" (
  "id_insumo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(50) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "descripcion" text,
  "id_unidad" int NOT NULL,
  "id_sede" int NOT NULL,
  "stock_minimo" int DEFAULT 0,
  "activo" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "inventario" (
  "id_inventario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_insumo" int UNIQUE NOT NULL,
  "cantidad" decimal(10,2) NOT NULL DEFAULT 0,
  "id_sede" int NOT NULL,
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "movimiento_inventario" (
  "id_movimiento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_inventario" int NOT NULL,
  "tipo" varchar(50) NOT NULL,
  "cantidad" decimal(10,2) NOT NULL,
  "motivo" varchar(255),
  "id_usuario" int NOT NULL,
  "fecha" timestamp DEFAULT (now())
);

CREATE TABLE "producto_insumo" (
  "id_producto_insumo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" int NOT NULL,
  "id_insumo" int NOT NULL,
  "cantidad_necesaria" decimal(10,2) NOT NULL
);

CREATE TABLE "pedido" (
  "id_pedido" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" int NOT NULL,
  "id_sede" int NOT NULL,
  "fecha" timestamp DEFAULT (now()),
  "estado" varchar(50) DEFAULT 'pendiente',
  "total" decimal(10,2) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "detalle_pedido" (
  "id_detalle" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_pedido" int NOT NULL,
  "id_producto" int NOT NULL,
  "cantidad" int NOT NULL,
  "precio_unitario" decimal(10,2) NOT NULL,
  "subtotal" decimal(10,2) NOT NULL
);

CREATE TABLE "reclamo" (
  "id_reclamo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_pedido" int NOT NULL,
  "id_cliente" int NOT NULL,
  "descripcion" text NOT NULL,
  "estado" varchar(50) DEFAULT 'abierto',
  "fecha" timestamp DEFAULT (now()),
  "fecha_resolucion" timestamp
);

CREATE TABLE "notificacion" (
  "id_notificacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" int NOT NULL,
  "mensaje" text NOT NULL,
  "fecha" timestamp DEFAULT (now()),
  "leida" boolean DEFAULT false
);

CREATE TABLE "proveedor" (
  "id_proveedor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "telefono" varchar(20),
  "email" varchar(255),
  "direccion" varchar(255),
  "activo" boolean DEFAULT true
);

CREATE TABLE "compra" (
  "id_compra" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_proveedor" int NOT NULL,
  "id_usuario" int NOT NULL,
  "fecha" date DEFAULT (now()),
  "total" decimal(10,2) NOT NULL,
  "estado" varchar(50) DEFAULT 'pendiente'
);

CREATE TABLE "detalle_compra" (
  "id_detalle_compra" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_compra" int NOT NULL,
  "id_insumo" int NOT NULL,
  "cantidad" decimal(10,2) NOT NULL,
  "precio_unitario" decimal(10,2) NOT NULL,
  "subtotal" decimal(10,2) NOT NULL
);

CREATE TABLE "sede" (
  "id_sede" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "direccion" varchar(255),
  "telefono" varchar(20),
  "activo" boolean DEFAULT true
);

CREATE TABLE "empleado" (
  "id_empleado" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int UNIQUE NOT NULL,
  "id_sede" int NOT NULL,
  "cargo" varchar(100),
  "fecha_ingreso" date NOT NULL
);

CREATE TABLE "administrador" (
  "id_admin" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int UNIQUE NOT NULL,
  "nivel_acceso" varchar(50) DEFAULT 'basico'
);

CREATE TABLE "turno" (
  "id_turno" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empleado" int NOT NULL,
  "fecha" date NOT NULL,
  "hora_inicio" time NOT NULL,
  "hora_fin" time NOT NULL
);

-- foreign keys (unchanged)
ALTER TABLE "cliente" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario") ON DELETE CASCADE;
ALTER TABLE "empleado" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario") ON DELETE CASCADE;
ALTER TABLE "administrador" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario") ON DELETE CASCADE;
ALTER TABLE "producto" ADD FOREIGN KEY ("id_unidad") REFERENCES "unidad_medida" ("id_unidad") ON DELETE RESTRICT;
ALTER TABLE "insumo" ADD FOREIGN KEY ("id_unidad") REFERENCES "unidad_medida" ("id_unidad") ON DELETE RESTRICT;
ALTER TABLE "insumo" ADD FOREIGN KEY ("id_sede") REFERENCES "sede" ("id_sede") ON DELETE RESTRICT;
ALTER TABLE "inventario" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo") ON DELETE CASCADE;
ALTER TABLE "movimiento_inventario" ADD FOREIGN KEY ("id_inventario") REFERENCES "inventario" ("id_inventario") ON DELETE CASCADE;
ALTER TABLE "movimiento_inventario" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario") ON DELETE RESTRICT;
ALTER TABLE "producto_insumo" ADD FOREIGN KEY ("id_producto") REFERENCES "producto" ("id_producto") ON DELETE CASCADE;
ALTER TABLE "producto_insumo" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo") ON DELETE CASCADE;
ALTER TABLE "pedido" ADD FOREIGN KEY ("id_cliente") REFERENCES "cliente" ("id_cliente") ON DELETE RESTRICT;
ALTER TABLE "pedido" ADD FOREIGN KEY ("id_sede") REFERENCES "sede" ("id_sede") ON DELETE RESTRICT;
ALTER TABLE "detalle_pedido" ADD FOREIGN KEY ("id_pedido") REFERENCES "pedido" ("id_pedido") ON DELETE CASCADE;
ALTER TABLE "detalle_pedido" ADD FOREIGN KEY ("id_producto") REFERENCES "producto" ("id_producto") ON DELETE RESTRICT;
ALTER TABLE "reclamo" ADD FOREIGN KEY ("id_cliente") REFERENCES "cliente" ("id_cliente") ON DELETE RESTRICT;
ALTER TABLE "reclamo" ADD FOREIGN KEY ("id_pedido") REFERENCES "pedido" ("id_pedido") ON DELETE RESTRICT;
ALTER TABLE "notificacion" ADD FOREIGN KEY ("id_cliente") REFERENCES "cliente" ("id_cliente") ON DELETE CASCADE;
ALTER TABLE "compra" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario") ON DELETE RESTRICT;
ALTER TABLE "compra" ADD FOREIGN KEY ("id_proveedor") REFERENCES "proveedor" ("id_proveedor") ON DELETE RESTRICT;
ALTER TABLE "detalle_compra" ADD FOREIGN KEY ("id_compra") REFERENCES "compra" ("id_compra") ON DELETE CASCADE;
ALTER TABLE "detalle_compra" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo") ON DELETE RESTRICT;
ALTER TABLE "empleado" ADD FOREIGN KEY ("id_sede") REFERENCES "sede" ("id_sede") ON DELETE RESTRICT;
ALTER TABLE "turno" ADD FOREIGN KEY ("id_empleado") REFERENCES "empleado" ("id_empleado") ON DELETE CASCADE;
ALTER TABLE reclamo ALTER COLUMN estado SET DEFAULT 'abierto';